export const  profiles=[
    {name:'Brian Kirui',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        id:'',
        isVisible:false
    },
    {name:'Anita Sofia',
        yearsActive:'2024-present',
        clubRoles:'Club President(2025)',
        accolades:'Cueta Debate Champion,Debate Novice Champion Mashujaa XIII, Cueta PS Champion',
        photo:'/anita.jpg',
        catchPhrase:'',
        alias:'Sofia The First',
        rumor:"She breaks hearts as often as she does debate rounds",
        passion:'Crotcheting',
        trainer:'',
        id:'',
        isVisible:true
    },
    {name:'Keneth Mwaniki',
        yearsActive:'2022-present',
        clubRoles:'Former Club President(2024)',
        alias:'Kenkei',
        accolades:'Cueta debate semi-finalist, Jabali PS semi-finalist, Best Debate Judge Illouwa II',
        photo:'/ken.jpg',
        catchPhrase:'',
        rumor:'',
        passion:'Sci-fi',
        trainer:'',
        id:'ken',
        isVisible:true
    },
    {name:'Wambugu Muhota',
        yearsActive:'2023-present',
        clubRoles:'Training Coordinator/Interim President 24-25',
        accolades:"Convenor ILO’UWA Debates II, CA Africa Child Debators Inaugural tournament,UNICONNECT Final Champions,KUDC 2.0 BEST JUDGE (PS),UNICONNECT Best Male Speaker, INDABA II BEST JUDGE (DEBATE),Athena Women’s Festival '24 - Finalist & 1st Runner Up,Kampala Opens Quarterfinalist, KUDC 1.0 Quarterfinalist, Mashujaa IX 2nd Best Novice Speaker",
        photo:'/ted.jpg',
        catchPhrase:'"Have you met Ted?"',
        alias:" Teddy 'THE' BEAR 🐻‍❄",
        rumor:'loves like Ted Mosby (mostly true😅😅😅) so the character development mileage on this nigga is real',
        passion:'Climate and Social Justice',
        trainer:'Associate Trainer at JUJA PRE SENIOR SCHOOL',
        id:'',
        isVisible:true
    },
    {name:'Kavithe Yvonne',
        yearsActive:'2022-present',
        clubRoles:' VP PR(2023)',
        accolades:"Semi-finalist Mashujaa 15, Semi-finalist Athena 1, Finalist Ilo'uwa 1.0, Semi-finalist Scholars debate '22",
        photo:'/yvonne.jpg',
        catchPhrase:'',
        alias:'Kavinye, Kavits',
        rumor:'only partners people of the opposite gender?',
        passion:'overthinking, and design',
        trainer:'Alliance Girls',
        id:'',
        isVisible:true
    },
    {name:'Lucy Osenyi',
        yearsActive:'2022-Present',
        clubRoles:'Secretary(2023-2024)',
        accolades:"7th best public speaker KUDC 2024,3rd best judge KUDC -Nyanza/Western Reginald 2025, Best Public Speaker CUETA 1.0, Novice Champion Ilo'uwa 1.0",
        photo:'/lucy.jpg',
        catchPhrase:'I feel like...',
        alias:'L.A',
        rumor:'',
        passion:'Adventure, Networking',
        trainer:'',
        id:'',
        isVisible:true
    },
    {name:'Desiree Mmasi',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        id:'',
        isVisible:false
    },
    {name:'Jeremy Weru',
        yearsActive:'2024-present',
        clubRoles:'Transport Co-ordinator(peer-pressured into it)',
        alias:'Mras',
        accolades:"Ill'ouwa 2 Novice Champion; KUDC PS 4th Best Judge",
        photo:'/jeremy.jpg',
        catchPhrase:'The absence of evidence, ...',
        rumor:'Strangers assume he loves herbs😂',
        passion:"Knowledge (He's legit a walking encyclopedia)",
        trainer:'',
        id:'',
        isVisible:true
    },
    {name:'Bridgette Musango',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        id:'',
        isVisible:false
    },
    {name:'Wanjiru Wanjiku',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        id:'',
        isVisible:false
    },
    {name:'Esther Mamai',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        id:'',
        isVisible:false
    },
    {name:'Esther Nyamwathi',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        id:'',
        isVisible:false
    },
    {name:'Peter Ndwati',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        id:'',
        isVisible:false
    },
    {name:'Victoria Kerubo',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        id:'',
        isVisible:false
    },
    {name:'George Kiritu',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        id:'',
        isVisible:false
    },
    {name:'Nina Wairimu',
        yearsActive:'2022-present',
        clubRoles:'Debater, chaos creator',
        accolades:"Uniconnect 2.0 champion, first Runner's up Athena women's tournament, EAUDC semi-finalist, KUDC 1.0 semi-finalist, 3rd best Public Speaking judge KUDC 2.0, Mashujaa ix novice semi-finalist, 4th best novice speaker Mashujaa ix (the list goes on..)",
        photo:'/nina.jpg',
        catchPhrase:'',
        alias:'',
        rumor:'She once almost won a tournament tipsy🤫',
        passion:'Discourse',
        trainer:'Various under The Debate Circle',
        id:'nina',
        isVisible:true
    },
    {name:'Ivan Oyunde',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        isVisible:false
    },
    {name:'Sandra Njoki',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        isVisible:false
    },
    {name:'Leon Ogola',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        isVisible:false
    },
    {name:'Gladwell Koech',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        isVisible:false
    },
    {name:'Brian Ikiara',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        isVisible:false
    },
    {name:'BP Ndolo',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        isVisible:false
    },
    {name:'Sylvia Njoroge',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        isVisible:false
    },
    {name:'Bonaventure Ogeto',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        isVisible:false
    },
    {name:'Maureen Njoroge',
        yearsActive:'',
        clubRoles:'',
        accolades:'',
        photo:'',
        catchPhrase:'',
        alias:'',
        rumor:'',
        passion:'',
        trainer:'',
        isVisible:false
    },
    {name:'Katherin Nkini',
        yearsActive:'2025-present',
        clubRoles:'',
        alias:'Kat',
        accolades:'Mashujaa XIV Debate Novice Semi-finalist',
        photo:'',
        catchPhrase:'',
        rumor:'',
        passion:'Ariana Grande',
        trainer:'',
        isVisible:false
    }       
];

export const authors= profiles.filter(e=>e.isVisible).map(p=>p.name);