
function Profiles(){
    const profiles=[
        {name:'Brian Kirui',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Anita Sofia',
            yearsActive:'2024-present',
            clubRoles:'Club President(2025)',
            accolades:'Cueta Debate Champion,Debate Novice Champion Mashujaa XIII, Cueta PS Champion',
            photo:'/anita.jpg',
            catchPhrase:'',
            alias:'Sofia The First',
            rumor:"She breaks hearts as often as she does debate rounds",
            passion:'Crotcheting',
            trainer:'',
            isVisible:true
        },
        {name:'Keneth Mwaniki',
            yearsActive:'2022-present',
            clubRoles:'Former Club President(2024)',
            alias:'Kenkei',
            accolades:'Cueta debate semi-finalist, Jabali PS semi-finalist, Best Debate Judge Illouwa II',
            photo:'/ken.jpg',
            catchPhrase:'',
            rumor:'',
            passion:'Sci-fi',
            trainer:'',
            isVisible:true
        },
        {name:'Jeremy Weru',
            yearsActive:'2024-present',
            clubRoles:'Transport Co-ordinator(peer-pressured into it)',
            alias:'Mras',
            accolades:"Ill'ouwa 2 Novice Champion; KUDC PS 4th Best Judge",
            photo:'/jeremy.jpg',
            catchPhrase:'The absence of evidence, ...',
            rumor:'Strangers assume he loves herbs😂',
            passion:"Knowledge (He's legit a walking encyclopedia)",
            trainer:'',
            isVisible:true
        },
        {name:'Desiree Mmasi',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Bridgette Musango',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Lucy Osenyi',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Wanjiru Wanjiku',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Esther Mamai',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Esther Nyamwathi',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Peter Ndwati',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Victoria Kerubo',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Yvonne Kavithe',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Wambugu Muhota',
            yearsActive:'2023-present',
            clubRoles:'Training Coordinator/Interim President 24-25',
            accolades:"Convenor ILO’UWA Debates II, CA Africa Child Debators Inaugural tournament,UNICONNECT Final Champions,KUDC 2.0 BEST JUDGE (PS),UNICONNECT Best Male Speaker, INDABA II BEST JUDGE (DEBATE),Athena Women’s Festival '24 - Finalist & 1st Runner Up,Kampala Opens Quarterfinalist, KUDC 1.0 Quarterfinalist, Mashujaa IX 2nd Best Novice Speaker",
            photo:'/ted.jpg',
            catchPhrase:'"Have you met Ted?"',
            alias:" Teddy 'THE' BEAR 🐻‍❄",
            rumor:'loves like Ted Mosby (mostly true😅😅😅) so the character development mileage on this nigga is real',
            passion:'Climate and Social Justice',
            trainer:'Associate Trainer at JUJA PRE SENIOR SCHOOL',
            isVisible:true
        },
        {name:'George Kiritu',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Nina Wairimu',
            yearsActive:'2022-present',
            clubRoles:'Debater, chaos creator',
            accolades:"Uniconnect 2.0 champion, first Runner's up Athena women's tournament, EAUDC semi-finalist, KUDC 1.0 semi-finalist, 3rd best Public Speaking judge KUDC 2.0, Mashujaa ix novice semi-finalist, 4th best novice speaker Mashujaa ix (the list goes on..)",
            photo:'/nina.jpg',
            catchPhrase:'',
            alias:'',
            rumor:'She once almost won a tournament tipsy🤫',
            passion:'Discourse',
            trainer:'Various under The Debate Circle',
            isVisible:true
        },
        {name:'Ivan Oyunde',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Sandra Njoki',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Leon Ogola',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Gladwell Koech',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Brian Ikiara',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'BP Ndolo',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Sylvia Njoroge',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Bonaventure Ogeto',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Maureen Njoroge',
            yearsActive:'',
            clubRoles:'',
            accolades:'',
            photo:'',
            catchPhrase:'',
            alias:'',
            rumor:'',
            passion:'',
            trainer:'',
            isVisible:false
        },
        {name:'Katherin Nkini',
            yearsActive:'2025-present',
            clubRoles:'',
            alias:'Kat',
            accolades:'Mashujaa XIV Debate Novice Semi-finalist',
            photo:'',
            catchPhrase:'',
            rumor:'',
            passion:'Ariana Grande',
            trainer:'',
            isVisible:false
        }       
    ];
    function profiler(d,i){
        if(d.isVisible)        
        return(
            <div className="profileCard" key={i}>
                <img src={d.photo} alt={d.name} style={{flexGrow:'1'}}/>
                <div className="profileDetails"style={{flexGrow:'2'}}>
                <h2 style={{margin:'0px'}}>{d.name}</h2>
                {d.alias!==''?<p><strong>Alias: </strong>{d.alias}</p>:''}
                {d.clubRoles!==''?<p><strong>Club Roles: </strong>{d.clubRoles}</p>:''}
                {d.accolades!==''?<p><strong>Accolades: </strong>{d.accolades}</p>:''}
                {d.trainer!==''?<p><strong>Training Expertise: </strong>{d.trainer}</p>:''}
                {d.passion!==''?<p><strong>Passionate About: </strong>{d.passion}</p>:''}
                {d.catchPhrase!==''?<p><strong>Catchprase: </strong>{d.catchPhrase}</p>:''}
                {d.rumor!==''?<p><strong>Rumor: </strong>{d.rumor}</p>:''}
                {d.yearsActive!==''?<p><strong>Years active: </strong>{d.yearsActive}</p>:''}
                </div>
            </div>
        )
    }

    return(
        <>
        <div className="textBlock">
            <h2>Meet our debators</h2>
        </div>
        {profiles.map((d,i)=>profiler(d,i))}
        </>
    );
}
export default Profiles